# Notes

## Caveats

- Preliminary
- Meta / synthetic
- Sociolinguistics
- Anticipate effects on medical practice 

## Major Topics

- Problem: How will LLMs transform biomedicine?
- Approach: LLMs as discourse models, knowledge; they are not other minds, any more than the settlement patterns studied by archaeologists are
- Theory
	- Thick mediation, communication, social AI
	- Computational sublimation, reproduction of knowledge
	- Study of discourse, discourse genres, codes
- Application
	- Discourse in the biomedical setting
	- LLMs in biomedicine -- sources, models, use cases
	- Effects

## Dimensions

Studies of large language models in the context of medicine usually focus on one of three dimensions:

- Data used to fine-tune language models
- Language models themselves, along with performance measures at various generic tasks
- Use cases for language models

The first and third can be broken down into discourse genres and communicative situations. For example patient records, or medical research literature as data input, and improving medical research or summarizing doctor's notes, or generating messages to patients as data output.

## Examples and Exhibits

### Prompt engineering as exemplary of planning vs situated action. 

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10585440/ 

This paper summarizes the current state of research about prompt engineering and, at the same time, aims at providing practical recommendations for the wide range of health care professionals to improve their interactions with LLMs.

Compare data sources for each of the emerging language models

How are models used? See use cases. How much planning?

Convert patient conversations 
https://techcrunch.com/2023/03/14/nabla-a-french-digital-health-startup-launches-copilot-using-gpt-3-to-turn-patient-conversations-into-actionable-items/ 

Diagnosis
https://www.statnews.com/2023/02/13/chatgpt-assisted-diagnosis/ 

Automating repetitive functions
https://www.thelancet.com/journals/landig/article/PIIS2589-7500(23)00021-3/fulltext 
this Lancet piece on the future of discharge summaries.

Scientific research
https://www.mdpi.com/2227-9032/11/6/887 

Generate health awareness messages
https://www.frontiersin.org/articles/10.3389/fcomm.2023.1129082 

Info retrieval and decision support
https://provectus.com/blog/comparison-large-language-models-biomedical-domain/ 

## Models 

| Model | Data | Uses |
|--------|-------|------|
| Meditron | Research publications | |

Gatortron
Clinical text

MultiMedQA


BioBERT


PubMedBERT


BioMegatron


ClinicalBERT


BLOOM

message generation


Meditron
https://github.com/epfLLM/meditron 

... adapted to the medical domain from Llama-2 through continued pretraining on a comprehensively curated medical corpus, including selected PubMed papers and abstracts, a new dataset of internationally-recognized medical guidelines, and a general domain corpus.

K -- Dr

Gatortron
https://www.nature.com/articles/s41746-023-00958-w 

This study develops a generative clinical LLM, GatorTronGPT, using 277 billion words of text including (1) 82 billion words of clinical text from 126 clinical departments and approximately 2 million patients at the University of Florida Health and (2) 195 billion words of diverse general English text

See https://medinform.jmir.org/2020/3/e17984/ on clinical text in machine learning 

The vast majority of studies focused on a single type of clinical narratives, which ranged from imaging reports to hospital discharge summaries. 

Table 2. Datasets used in clinical natural language processing community challenges.
Dataset	Provenance	Documents	Size	Annotations	Studies
- 2010 i2b2/VA [123]	
	- PHCb, BIDMCc, UPMCd	
	- Discharge summaries, progress reports	
	- 871	
	- Medical problems, treatments, tests, and relations among them	
	- [20,49,64,67,96,104]
- 2011 i2b2/VA [124]	
	- PHC, BIDMC, UPMC, Mayoe	
	- Discharge summaries, progress reports, radiology reports, pathology reports, other reports	
	- 978+164	
	- Coreference chains for the problem, person, test, result, treatment, anatomical site, disease or syndrome, sign or symptom, etc	
	- [63]
- 2012 i2b2 [125]	
	- PHC, BIDMC	
	- Discharge summaries	
	- 310	
	- Clinical events, temporal expressions, temporal relations	
	- [64]
- 2013 ShARe/CLEF eHealth [126]	
	- BIDMC	
	- Discharge summaries, electrocardiogram reports, echocardiogram reports, radiology reports	
	- 300	
	- Disorders, acronyms, and abbreviations	
	- [54,57,88,98,114]
- 2014 i2b2/UTHealth [127,128]	
	- PHC	
	- Longitudinal medical records	
	- 1304	
	- Protected health information; risk factors for heart disease	
	- [18,21,26,52,62,64,80,82,91,107,108]
- 2015 SemEval/THYME [129]	
	- Mayo	
	- Clinical notes, pathology reports	
	- 600	
	- Times, events, and temporal relations among them	
	- [60]
- 2016 CEGS N-GRID [130,131]	
	- PHC	
	- Psychiatric intake records	
	- 1000	
	- Protected health information; symptom severity	
	- [23,27,42,53,58,65,78,83,92]

See "A Sociolinguistic Analysis of Doctor-Patient Communication." M. Simmons. Published 31 January 1998
https://www.diigo.com/0uuj8a 

Consider Suchman -- plans vs situated action

Medicine as situated action

LLMs and planning ... Prompt engineering and planning. 

Denial of situation.

Dr -- Dr
Pt -- Dr

MultiMedQA
https://www.nature.com/articles/s41586-023-06291-2

... a benchmark combining six existing medical question answering datasets spanning professional medicine, research and consumer queries and a new dataset of medical questions searched online, HealthSearchQA. We propose a human evaluation framework for model answers along multiple axes including factuality, comprehension, reasoning, possible harm and bias.

Pt -- K 

Slides
1. Introduction / Objectives
	1. I want to describe the effect that LLMs may have on the communication and reproduction of knowledge in the context of biomedicine
		1. Formal education is a special case of knowledge reproduction
		2. Education is ongoing; lifelong learning + specific cases
	2. I want to introduce a frame for discovering and making sense of these effects
2. First, some example Uses
	1. ChatGPT and Dr-Pt relations
	2. GatorTron, etc. for information retrial, document summarization
3. What are LLMs?
	1. LLMs are primarily language generators
		1. They are "intelligent" only to the degree that intelligence is consists of coherent sentences
		2. They possess "knowledge" on to the extent that the sentences they generate are mappable to realia and qualia (things and experiences)
	2. Proper study is in terms of language
4. Knowledge (Aside)
	1. LLMs do not meet basic criterion of Justified True Belief
		1. Beliefs: Mental representations
		2. Truth: Correspondance, Coherence, Pragmatic 
		3. Justification: Experience, Experiment, Reason
	2. LLMs?
5. Language
	1. Grammar vs Discourse
	2. LLMs do not have a grammar per se
	3. LLMs model discourse
6. Communication
	1. Discourse
	2. Thick Mediation
	3. Characterized by discourse Genres
	4. Formal and Informal Models
7. Discourse Genres 
	1. Conditioned by Relationship Types
8. Relationship Types
	1. Formal and informal genres for each
	2. Doctor -- Doctor: Notes, EMR, EHR
	3. Doctor -- Patient: MyChart messaging
	4. Patient -- Patient: Reddit
	5. K -- Doctor: Research reports, secondary and tertiary sources
	6. K -- Patient: WebMD
9. Effects of LLMs

Prompt engineering guides are effectively guides for how to speak. 

https://www.linkedin.com/posts/eric-vyacheslav-156273169_game-changer-open-ai-just-released-their-activity-7141454141683343360-eunF

https://platform.openai.com/docs/guides/prompt-engineering 

Latest
- LLMs mediate communication 
	- Therefore, LLMs structure relationships 
	- Therefore, LLMs structure language
	- Therefore, LLMs structure knowledge
- Thick mediation
	- Shannon's model = thin mediation
	- Licklider's model = thick mediation
- Effects on language
	- Characterized by discourse genres
		-  Genres may be defined by their sociocultural and pragmatic characteristics,
			- sociocultural dimension: the culture where it is embedded
			- pragmatic dimension: immediate situation where it takes place
			- textual dimension the structural and linguistic
		- Genres are "situated" forms of cognition within specific social activities
	- Genres vary by the differences in the elements of the 4-part model of speech
		- Event, Locution, Illocution, Perlocution
		- Implied social relationship embedded in context, situation, environment, etc.
	- Language characterized by codes
		- Restricted codes
- Effects on relationships
	- Look at relationship types
- Effects on knowledge
	- Formal vs informal knowledge transmission
- Examples
	- Informal
		- EMR, EHR, MyChart messaging, visit transcripts
	- Formal
		- Research reports (PubMed), protocols

Angles
- BMDS in terms of model of DS
	- BM as domain knowledge
	- Specific pipeline -- Bioinformatics as DESIGN, Biostatistics and ML as ANALYTICS
- BMDS in terms of history (offer in support of model)
	- VA Data Sciences Division
	- AF School of Aerospace Medicine
	- Glaxo Smith Klein Data Science
- BMDS in terms of sociology of AI
	- Thick mediation
	- Role of LLMs 
	- Effects on language
- BDMS as a specific body of knowledge
- Language and Knowledge
- Similar to historian's concern

Quotes
- Chesterton on the madman and reason.
- Lyotard on the condition of knowledge.
- Douglas:"institutions are machines for thinking."

Talking Points / Outline
- Preface
	- Unapologetically high level talk
	- Purpose is to frame the subject
- Theoretical Framework
	- Scientific knowledge is significantly mediated by language
		- "Knowledge is a text-based application"
		- Fundamental to human cognition
		- Fundamental to the transmission of knowledge over space and time
		- Language functions as both a medium of thought and communication
	- Communication precedes thought (Durkheim, Douglas)
		- Captured in concept of discourse
		- "Institutions do the classification"
		- Knowledge is largely stored language
	- Two primary forms of communication in scientific education
		- Formal knowledge: student, mediated by instructors, the library
		- Informal knowledge:
	- The situation of teaching and learning
		- The concern for plagiarism pales in comparison to the effects of LLMs on the condition of knowledge
- Thesis
	- LLMs may be viewed as institutional frameworks
		- An AI is not a brain; it is a social arrangement
			- Consistent with Hobbes' view of society
		- Douglas: Institutions do the classifying
	- LLMs will shape how knowledge is constituted
		- What survives
		- How it will survive
	- Epistemic imperialism
	- Formal : informal :: Structure  : Unstructured
	- Insurance and classification driving healthcare decision-making
	- What gets recorded 
- Application to BMDS
	- What is BMDS
		- Specific characteristics
		- Areas
			- Computational Genomics
			- Biostatistics
			- Text mining EHRs
	- Historical background
		- VA, AFSAM, GSK, etc.
	- Current conditioning factors
		- COVID
			- Telemedicine
			- Surveillance and social control
		- Predictive Analytics
		- LLMs and Generative AI
- LLMs and language
	- Standardization of language
	- Detachment from reference
- Anticipated effects
	- Databasing of knowledge

References

Resources
- 2020 Talk on Telemedicine
	- 
- 2019 Talk on AI
	- https://docs.google.com/presentation/d/1FkhsBaeIQAEB7yC8nZ6op068KRAjv6LIAUvMtSGDjHs/edit?usp=drive_web